export const apiURL = ': https://jsonplaceholder.typicode.com/photos'; // Production


export const apiEndpoints = {
  login: '/Login',
  logout: '/Signout',
  getUser: '/UserProfile',
  getPreferences: '/Preferences',
  getTravelList: '/TravelList',
  getTravelDetail: '/TravelDetail',
  getVehicleDetail: '/VehicleDetail',
  getSlides: '/HomeImage',
  getTrackingList: '/TrackingList',
  getTrackingDetail: '/TrackingDetail',
  getVehicleLogos: '/Logos',
  getComplaintList: '/ComplaintList',
  getComplaintDetail: '/ComplaintVINDetail',
  getVinsList: '/VehicleList',
  getDamageCatalog: '/DamageCatalogList',
  getNotifications: '/NotificationList',
  getNotificationCounter: '/NotificationCounter',
  getDamageList: '/ComplaintDetail',
  getUserMenu: '/UserMenu',
  setSurvillance: '/TravelSuvervillance',
  setNotificationReaded: '/NotificationCounter',
  sendComplaint: '/ComplaintGenerate',
  sendScore: '/TravelScore',
  sendProfile: '/UserProfile',
  getCD: '/VINCDList',
  getYards: '/VINCDYardList',
  getTrans: '/VINCDTransList',
  getVinCDList: '/VINCDVinList',
  getReportType: '/ReportTypesList',
  getReportList: '/ReportByTypeList',
  getReportFile: '/ReportFile'
};
